[package]
name = "bl3_save_edit_ui"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bl3_save_edit_core = { path = "../bl3_save_edit_core" }
rusttype = "0.9"
native-dialog = "0.4"
rayon = "1.5"
tokio-rayon = "2.1"
futures = "0.3"

[dependencies.tokio]
version = "1"
features = ["fs", "rt-multi-thread", "rt"]

[dependencies.strum]
version = "0.21"
features = ["derive"]

[dependencies.iced]
git = "https://github.com/hecrj/iced"
rev = "1b6cf05"
features = ["tokio"]
